### PR TITLE
Resolves #61

### LINKED ISSUE #61: Grunt Tasks not progressing
Hi I have installed both the Grunt Module and ImageMagick( I know this is installed as the image convert method is working) however the Grunt task gets stuck at Running "favicons:icons" and never seems to progress, anyone got any ideas or had similar issues? My set up for the task is:
`favicons: {
			icons: {
				src: 'logo.png',
				dest: '<%= destPath %>logos'
			}
		}`

Any help appreciated

Robert

### PR DESCRIPTION
**Pull request by qasimalyas**
This change resolves https://github.com/gleero/grunt-favicons/issues/61

### CODE REVIEW

**Comment by garygreen** [comment]
@gleero any news on this? grunt-favicons is broken on windows without the update to sync-exec. This PR works perfectly

**Comment by garygreen** [comment]
Thanks !

**Comment by qasimalyas** [comment]
@gleero I don't think this has this been published to NPM? For the past few projects i've used grunt-favicons on i've had to manually go in and update the package.json, then update to get it to work.

**Comment by viktorbijlenga** [comment]
@qasimalyas This fix is published on NPM. Make sure your package.json is installing grunt-favicons@0.7.0

**Pull request merged**
